### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Wangshuai8156** [whitecloudy/wisp5_436kHz-40kHz#2]
Do I only need to build and debug Project run-once and Project simpleAckDemo in CCS? Do other projects need to be programmed into MSP430?

**Comment by whitecloudy** [comment]
It depends on what you want to do. If you want just simple Query and EPC ID communication, build and debug those two projects would be enough. Otherwise, you need to compile other projects or you need to make it on your own.

**Comment by Wangshuai8156** [comment]
Have you tried to read WISP5 with USRP? I used your code and changed the parameter settings of usrp according to the protocol summary, but the reader did not read the EPC. Is there anything worth noting if I want to use it on usrp?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitecloudy/wisp5_436kHz-40kHz"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 凌晨0:07
收件人:&nbsp;"whitecloudy/wisp5_436kHz-40kHz"<wisp5_436kHz-40kHz@noreply.github.com&gt;;
抄送:&nbsp;"心有灵犀"<1114112081@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [whitecloudy/wisp5_436kHz-40kHz] How to run it? (#2)





 
It depends on what you want to do. If you want just simple Query and EPC ID communication, build and debug those two projects would be enough. Otherwise, you need to compile other projects or you need to make it on your own.

**Comment by whitecloudy** [comment]
Yes, I did. Honestly, those 436kHz-40kHz branch is mainly for my own work. So it might not work on basic USRP epc gen2 code. It would be better to check that the WISP is awake and answered the reader's query.(by insert some code or anything....)

**Comment by Wangshuai8156** [comment]
Thank you for your reply. I have some questions as follows.
(1) The USRP code I used is the code of Nikos Kargas (https://github.com/nkargas/Gen2-UHF-RFID-Reader), basically there is no major modification (just based on your protocol summary, Tari, Link Frequency, RTCal, TRCal and other parameters have been changed). If&nbsp;I want to make the USRP code and your WISP code communicate with each other, what changes do I need to make to the USRP code?Or can you provide your USRP code? It would be greatly appreciated if you could.
(2) You said that you can insert some code to check the status of WISP. What kind of code should I add? I really want to know whether WISP is awakened and whether it responds to USRP Query? Can you give an example? (For example, whether to observe through CCS or through blinking on WISP)
I just touched on WSIP related content, thank you for your guidance.
Looking forward to your reply！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitecloudy/wisp5_436kHz-40kHz"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 中午12:57
收件人:&nbsp;"whitecloudy/wisp5_436kHz-40kHz"<wisp5_436kHz-40kHz@noreply.github.com&gt;;
抄送:&nbsp;"心有灵犀"<1114112081@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [whitecloudy/wisp5_436kHz-40kHz] How to run it? (#2)





 
Yes, I did. Honestly, those 436kHz-40kHz branch is mainly for my own work. So it might not work on basic USRP epc gen2 code. It would be better to check that the WISP is awake and answered the reader's query.(by insert some code or anything....)

**Comment by Wangshuai8156** [comment]
I'm sorry to disturb you again. The two issues mentioned in the last email still puzzle me. I am very eager for you to answer my confusion. I would be grateful. Looking forword to&nbsp;your reply in your free time.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitecloudy/wisp5_436kHz-40kHz"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 中午12:57
收件人:&nbsp;"whitecloudy/wisp5_436kHz-40kHz"<wisp5_436kHz-40kHz@noreply.github.com&gt;;
抄送:&nbsp;"心有灵犀"<1114112081@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [whitecloudy/wisp5_436kHz-40kHz] How to run it? (#2)





 
Yes, I did. Honestly, those 436kHz-40kHz branch is mainly for my own work. So it might not work on basic USRP epc gen2 code. It would be better to check that the WISP is awake and answered the reader's query.(by insert some code or anything....)

**Comment by whitecloudy** [comment]
Sorry for the late reply. I was busy this whole weekend.

1) You need to check "global.h" file in CCS/wisp-base. "wisp-base" dir has a lot of basic codes which are shared for those project.
2) Just count the value and write on some memory. I usually use 0x1800(Normally used for RN16 random seed). See 40kHz_for_EPCtest branch, WISP_doRFID.asm line 143. You better understand the whole procedure of the codes first.
